export const commonWords = {
  en: [
    'the', 'be', 'of', 'and', 'a', 'to', 'in', 'he', 'have', 'it', 'that', 'for', 'they', 'I', 'with', 'as', 'not', 'on', 'she', 'at', 'by', 'this', 'we', 'you', 'do', 'but', 'from', 'or', 'which', 'one', 'would', 'all', 'will', 'there', 'say', 'who', 'make', 'when', 'can', 'more', 'if', 'no', 'man', 'out', 'other', 'so', 'what', 'time', 'up', 'go', 'about', 'than', 'into', 'could', 'state', 'only', 'new', 'year', 'some', 'take', 'come', 'these', 'know', 'see', 'use', 'get', 'like', 'then', 'first', 'any', 'work', 'now', 'may', 'such', 'give', 'over', 'think', 'most', 'even', 'find', 'day', 'also', 'after', 'way', 'many', 'must', 'look', 'before', 'great', 'back', 'through', 'long', 'where', 'much', 'should', 'well', 'people', 'down', 'own', 'just', 'because', 'good', 'each', 'those', 'feel', 'seem', 'how', 'high', 'too', 'place', 'little', 'world', 'very', 'still', 'nation', 'hand', 'old', 'life', 'tell', 'write', 'become', 'here', 'show', 'house', 'both', 'between', 'need', 'mean', 'call', 'develop', 'under', 'last', 'right', 'move', 'thing', 'general', 'school', 'never', 'same', 'another', 'begin', 'while', 'number', 'part', 'turn', 'real', 'leave', 'might', 'want', 'point', 'form', 'off', 'child', 'few', 'small', 'since', 'against', 'ask', 'late', 'home', 'interest', 'large', 'person', 'end', 'open', 'public', 'follow', 'during', 'present', 'without', 'again', 'hold', 'govern', 'around', 'possible', 'head', 'consider', 'word', 'program', 'problem', 'however', 'lead', 'system', 'set', 'order', 'eye', 'plan', 'run', 'keep', 'face', 'fact', 'group', 'play', 'stand', 'increase', 'early', 'course', 'change', 'help', 'line',
  ],
  vi: [
    'và', 'của', 'là', 'có', 'những', 'trong', 'một', 'các', 'không', 'cho', 'được', 'với', 'người', 'đã', 'khi', 'này', 'đến', 'để', 'về', 'nhiều', 'như', 'trên', 'làm', 'từ', 'ra', 'cũng', 'theo', 'vào', 'sẽ', 'lại', 'việc', 'hơn', 'sau', 'nhưng', 'mà', 'còn', 'phải', 'năm', 'nhà', 'chỉ', 'đó', 'ngày', 'rất', 'thì', 'tại', 'đang', 'nước', 'Việt', 'Nam', 'lớn', 'mới', 'hai', 'khác', 'đi', 'công', 'bộ', 'thể', 'biết', 'nói', 'thấy', 'hết', 'lên', 'họ', 'cùng', 'nơi', 'khiến', 'chưa', 'đây', 'vẫn', 'đều', 'điều', 'gì', 'khi', 'số', 'tới', 'tháng', 'ông', 'bà', 'con', 'sự', 'tay', 'mình', 'lúc', 'nên', 'qua', 'giữa', 'trước', 'thực', 'đường', 'thế', 'tính', 'chính', 'nhất', 'nào', 'cách', 'vì', 'mọi', 'đặt', 'nhau', 'thành', 'đầu', 'do', 'bằng', 'giá', 'mặt', 'ấy', 'tổ', 'chức', 'quốc', 'gia', 'đại', 'học', 'kinh', 'tế', 'xã', 'hội', 'văn', 'hóa', 'giáo', 'dục', 'y', 'tế', 'khoa', 'học', 'kỹ', 'thuật', 'thông', 'tin', 'truyền', 'thông', 'xây', 'dựng', 'giao', 'thông', 'vận', 'tải', 'nông', 'nghiệp', 'phát', 'triển', 'nông', 'thôn', 'tài', 'nguyên', 'môi', 'trường', 'lao', 'động', 'thương', 'binh', 'xã', 'hội', 'tư', 'pháp', 'kế', 'hoạch', 'đầu', 'tư', 'tài', 'chính', 'ngân', 'hàng', 'công', 'thương', 'du', 'lịch', 'thể', 'thao', 'văn', 'nghệ', 'nghệ', 'thuật', 'điện', 'ảnh', 'sân', 'khấu', 'âm', 'nhạc', 'mỹ', 'thuật', 'nhiếp', 'ảnh', 'báo', 'chí', 'xuất', 'bản', 'phát', 'thanh', 'truyền', 'hình',
  ],
  zh: [
    '的', '一', '是', '在', '不', '了', '有', '和', '人', '这', '中', '大', '为', '上', '个', '国', '我', '以', '要', '他', '时', '来', '用', '们', '生', '到', '作', '地', '于', '出', '就', '分', '对', '成', '会', '可', '主', '发', '年', '动', '同', '工', '也', '能', '下', '过', '子', '说', '产', '种', '面', '而', '方', '后', '多', '定', '行', '学', '法', '所', '民', '得', '经', '十', '三', '之', '进', '着', '等', '部', '度', '家', '电', '力', '里', '如', '水', '化', '高', '自', '二', '理', '起', '小', '物', '现', '实', '加', '量', '都', '两', '体', '制', '机', '当', '使', '点', '从', '业', '本', '去', '把', '性', '好', '应', '开', '它', '合', '还', '因', '由', '其', '些', '然', '前', '外', '天', '政', '四', '日', '那', '社', '义', '事', '平', '形', '相', '全', '表', '间', '样', '想', '向', '道', '命', '此', '位', '理', '望', '常', '教', '育', '光', '白', '路', '带', '风', '回', '南', '北', '东', '西', '声', '色', '走', '看', '知', '听', '问', '答', '打', '做', '给', '带', '帮', '助', '爱', '喜', '欢', '笑', '哭', '跑', '跳', '吃', '喝', '睡', '觉', '梦', '想', '念', '书', '写', '字', '画', '图', '唱', '歌', '舞', '蹈',
  ],
}
